Word of the day #3
alephium/docs pull request #76
Opened 2022-09-08 12:07 UTC by JKtranslator

Block Time
Bridge
Genesis Block
Hard Fork
UTXO

2022-09-08 18:29 UTC, Sakrecoer requested changes
Thanks @JKtranslator, found a couple of typos and suggestions. Please adjust accordingly. I'll gladly merge tomorrow morning if you'd rather call today a day :)

2022-09-08 18:29 UTC, Sakrecoer commented on docs/project/glossary.md
> +Alephium network has a difficult adjustment on every block and has an expected block time of **64 seconds**.
alephium has a _difficulty_ adjustement on....

2022-09-08 18:29 UTC, Sakrecoer commented on docs/project/glossary.md
> +Adittional resources: [Block Time and Block Size Article](https://medium.com/@alephium/block-time-and-block-size-16e37292444f)
Additional (two "D" one "T")

2022-09-08 18:29 UTC, Sakrecoer commented on docs/project/glossary.md
> +A Genesis Block is the name of a blockchain’s first block ever mined. As the blocks get layered—one on top of the other, the Genesis Block is the foundation or beginning of it.
"As the blocks get layered on top of each other." 

Maybe it's enough to either remove the `—`

2022-09-08 18:29 UTC, Sakrecoer commented on docs/project/glossary.md
> +[UTXO](https://en.wikipedia.org/wiki/Unspent_transaction_output) (unspent transaction output) is the term for the amount of a specific currency that remains unspent after a cryptocurrency transaction
(Unspent Transaction Output) 
I would capitalize the first letter to emphasis that it is the long version of the acronym.

2022-09-08 20:54 UTC, JKtranslator commented on docs/project/glossary.md
> +Alephium network has a difficult adjustment on every block and has an expected block time of **64 seconds**.
changed

2022-09-08 20:55 UTC, JKtranslator commented on docs/project/glossary.md
> +Adittional resources: [Block Time and Block Size Article](https://medium.com/@alephium/block-time-and-block-size-16e37292444f)
changed

2022-09-08 20:55 UTC, JKtranslator commented on docs/project/glossary.md
> +A Genesis Block is the name of a blockchain’s first block ever mined. As the blocks get layered—one on top of the other, the Genesis Block is the foundation or beginning of it.
changed

2022-09-08 20:55 UTC, JKtranslator commented on docs/project/glossary.md
> +[UTXO](https://en.wikipedia.org/wiki/Unspent_transaction_output) (unspent transaction output) is the term for the amount of a specific currency that remains unspent after a cryptocurrency transaction
changed

2022-09-09 06:34 UTC, Sakrecoer approved these changes
Awesome! Good catch on ttitle capitalization!! Many thanks! Have a great day!!

2022-09-09 06:34 UTC, merged